### ISSUE TITLE
Can get a text tweet instead of a dungeon

### ISSUE THREAD

**Issue by rburgess13** [AJFaraday/tiny_dungeon_player#18]
http://tdp.andrewfaraday.com/732391594712698880

![image](https://cloud.githubusercontent.com/assets/18577122/15320026/3584f81e-1c26-11e6-9451-f4cd893768b6.png)

**Comment by AJFaraday** [comment]
This is hillarious, thanks for letting me know! :smile: 

Oddly, this looks a little different in Firefox on Linux

![snapshot321](https://cloud.githubusercontent.com/assets/237798/15322353/2ea11402-1c34-11e6-928a-17f9087924fe.png)

Either way, it should guard against this:

* Detect if a tweet is actually a dungeon
* If not (or if tweet id returns nothing), go to the next tweet on the timeline.

This may harm performance, but it will allow us to skip these problems.

**Comment by SwartzCr** [comment]
you could also just check to see if it's a re-tweet or not, or I can like un-retweet this after the event, sorry sorry

**Comment by AJFaraday** [comment]
@SwartzCr I did consider just asking you to delete it again, but the TDP really should be able to handle the occasional alphanumeric tweet and just skip over it.

**Comment by AJFaraday** [comment]
I've added a check for non-dungeon tweets. Any alphanumeric characters will trigger a second call to grab the timeline from that point and check through until one of them is a dungeon. It takes half a second longer while stepping over tweets, but they no longer scupper the app.
