### ISSUE TITLE
breaks on firefox 38

### ISSUE THREAD

**Issue by SwartzCr** [AJFaraday/tiny_dungeon_player#4]
```
(process:15073): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
console.error: 
  [CustomizableUI]
  Custom widget with id loop-button does not return a valid node
```
page loads empty

**Comment by SwartzCr** [comment]
that was Mozilla Iceweasel 38.3.0

but works totally fine in firefox 42.0

**Comment by AJFaraday** [comment]
This looks like it was this issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1097597

I'm not sure if I can do anything more about it.
