### ISSUE TITLE
doors shouldn't be doors

### ISSUE THREAD

**Issue by SwartzCr** [AJFaraday/tiny_dungeon_player#6]
there are no doors, they should be treated just as different colored floor tiles, sorry for the confusion

**Comment by AJFaraday** [comment]
I'm not completely sure about this one, the trouble is that if the brown tiles are visible, monsters will be able to see the user from an alarming distance and round a surprising amount of corners. 

Currently there's a lot of tactics around when to enter a room and what to do next.

I'm willing to try it, but there's a good chance it'll go back to the same mechanics.

To implement as suggested:

* User stores the last tile it stepped onto
* When moving, current position is replaced with the previous tile
* Rename 'door' to 'passage'
* Make it's type 'floor'

Possible compromise:

* Change 'can see' algorithm to be based on a 'transparent' attribute
* set floors to 'transparent'
* User stores the last tile it stepped onto
* When moving, current position is replaced with the previous tile
* Anything walked through gets 'transparent' set true.
* Rename 'door' to passage
* Change the message to "You cleared the passage"

That would leave the game dynamic the way it is.

**Comment by SwartzCr** [comment]
well thinking about how this actually works in something like nethack, monsters can see you in passages, and follow you through them, but they typically have a set distance which they can see, like 6 tiles or something. So maybe there's a way for them to only see you if you're close to them

**Comment by AJFaraday** [comment]
That makes a lot of sense, I can modify the line-of-sight algorithm to only return true if the path between points is less than a given distance.

This also opens the option of having 'aggro' as an attribute for monsters. Smaller, low-damage monsters might actively persue the player over long distances, even in the next room, while your dragons and demons might not care until the player attacks them.

**Comment by AJFaraday** [comment]
I've given monsters a sight range (currently 4 steps by default), and they won't follow the player beyond that range.

I've removed all traces of doors from the application, replacing them with a passage, which is a type of floor.

When a tile moves, or dies, it is replaced with the last type of floor it stepped on.
