### ISSUE TITLE
Red face should be berserk

### ISSUE THREAD

**Issue by SwartzCr** [AJFaraday/tiny_dungeon_player#7]
look! He's so berserk! He should have more attack but less health maybe?

**Comment by AJFaraday** [comment]
When things get a little more complex, distinct characteristics of player emoji are a definite probability.

Do you imagine the berserkness changing his hit chance at all?

**Comment by AJFaraday** [comment]
I've defined emoji-specific player attributes, including the berserker, in player_types.js (https://github.com/AJFaraday/tiny_dungeon_player/blob/master/public/script/tdp/data/player_types.js)

For the time being berserker is triple damage and half health.
